var config = {}
config.aws = {}
config.aws.region = 'eu-west-1'
config.aws.s3 = {}
config.aws.s3.bucket= 'talkclass-ireland-tcbucket3332'
config.aws.s3.bucketresized = 'talkclass-ireland-tcbucket3332-resized'
config.aws.apigateway = {}
config.aws.apigateway.endpoint = 'https://p5gd9ec40a.execute-api.eu-west-1.amazonaws.com'
config.aws.apigateway.stage = '/dev'
config.aws.apigateway.name = '/talkclass'
config.roles = {}
config.roles.teacher = 'Teacher'
config.roles.parent = 'Parent'
module.exports= config
